name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: |
        ls
        cd ton
        git submodule update --init --recursive
    - name: mkdir
      run: |
        mkdir build
    - name: cmake
      run: | 
        cd build
        cmake ..
    - name: make -j4
      run: |
        cd build
        make -j4
    - name: find & copy binaries
      run: |
        mkdir artifacts
        for x in `find build -type f -perm -u+x`; do cp -av $x artifacts/;done
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: artifacts
