name: C/C++ CI MacOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: |
        ls
        cd ton
        git submodule update --init --recursive
    - name: install deps
      run: |
        brew install cmake openssl 
    - name: mkdir
      run: |
        mkdir build
    - name: cmake
      run: | 
        cd build
        cmake .. -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl
    - name: make -j4
      run: |
        cd build
        make -j4
        mkdir bins
        cp crypto/fift crypto/adjust-block crypto/dump-block crypto/tlbc crypto/func crypto/create-state validator-engine-console/validator-engine-console tonlib/tonlib-cli tonlib/libtonlibjson.so.0.5 tddb/io-bench http/http-proxy tdnet/udp_ping_pong tdnet/tcp_ping_pong rldp-http-proxy/rldp-http-proxy dht-server/dht-server lite-client/lite-client validator-engine/validator-engine utils/generate-random-id utils/pack-viewer utils/json2tlo adnl/adnl-proxy adnl/adnl-pong bins

    - uses: actions/upload-artifact@master
      with:
        name: bins
        path: build/bins/
