name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: |
        ls
        cd ton
        git submodule update --init --recursive
        cd ..
    - name: mkdir
      run: |
        mkdir build
        cd build
        pwd
        ls
    - name: cmake
      run: | 
        pwd
        ls
        cmake ..
    - name: make -j2
      run: make -j2
