name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: srt32/git-actions@v0.0.3
    - args: git submodule update --init --recursive
    - name: mkdir
      run: |
        mkdir build
        cd build
        pwd
    - name: cmake
      run: cmake ../ton
    - name: make -j2
      run: make -j2
