name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        depth: 1
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: Bedzior/run-cppcheck@master
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output
    - name: mkdir
      run: |
        mkdir build
    - name: cmake
      run: | 
        cd build
        cmake ..
    - name: make -j4
      run: |
        cd build
        make -j4
    - name: find & copy binaries
      run: |
        mkdir artifacts
        for x in `find build -type f -perm -u+x`; do cp -av $x artifacts/;done
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: artifacts
